# Generated by Django 4.0.4 on 2022-05-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0002_alter_strategy_options_strategy_best_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(blank=True)),
                ('strategy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.strategy')),
            ],
        ),
    ]
