# Generated by Django 4.0.4 on 2022-05-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting_app', '0002_alter_strategyconfig_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyconfig',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
