# Generated by Django 4.0.4 on 2022-05-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_alter_strategy_best_config'),
        ('backtesting_app', '0003_rename_strategy_id_strategyconfig_strategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategyconfig',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('number_of_trades', models.IntegerField()),
                ('winning_trades', models.FloatField()),
                ('profit', models.FloatField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.strategy')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
