
# Order types
_ORDER_TYPE_UNSPECIFIED = 0
_ORDER_TYPE_LIMIT = 1
_ORDER_TYPE_MARKET = 2


ORDER_TYPES = (
    (_ORDER_TYPE_LIMIT, 'Limit'),
    (_ORDER_TYPE_MARKET, 'Market')
)



# Direction types
_DIRECTION_TYPE_UNSPECIFIED = 0
_DIRECTION_TYPE_BUY = 1
_DIRECTION_TYPE_SELL = 2


DIRECTION_TYPES = (
    (_DIRECTION_TYPE_BUY, 'Buy'),
    (_DIRECTION_TYPE_SELL, 'Sell')
)