# Generated by Django 4.0.4 on 2022-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('file_name', models.CharField(max_length=100)),
                ('best_stock', models.CharField(max_length=100, null=True)),
                ('best_profit', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
