# Generated by Django 4.0.4 on 2022-05-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Стратегия', 'verbose_name_plural': 'Стратегии'},
        ),
        migrations.AddField(
            model_name='strategy',
            name='best_config',
            field=models.JSONField(blank=True, default='Empty'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='best_profit',
            field=models.CharField(blank=True, default='Empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='best_stock',
            field=models.CharField(blank=True, default='Empty', max_length=100),
        ),
    ]
