# Generated by Django 4.0.4 on 2022-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_strategy_options_strategy_best_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='best_config',
            field=models.JSONField(blank=True, default={'Config': 'Empty'}),
        ),
    ]
