
CANDLE_INTERVAL_1_MIN = 1
CANDLE_INTERVAL_5_MIN = 2
CANDLE_INTERVAL_15_MIN = 3
CANDLE_INTERVAL_HOUR = 4
CANDLE_INTERVAL_DAY = 5

INTERVALS = (
    (CANDLE_INTERVAL_1_MIN, '1 минута'),
    (CANDLE_INTERVAL_5_MIN, '5 минут'),
    (CANDLE_INTERVAL_15_MIN, '15 минут'),
    (CANDLE_INTERVAL_HOUR, '1 час'),
    (CANDLE_INTERVAL_DAY, '1 день'),
)